version: '3.7'

services:
  alchemyex:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: alchemyex_api
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - ./:/app
    depends_on:
      - alchemyex_db
      - alchemyex_redis
    networks:
      - alchemyex_network
  alchemyex_db:
    image: postgres:latest
    container_name: alchemyex_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - pg:/var/lib/postgresql/data
    networks:
      - alchemyex_network
  alchemyex_redis:
    image: redis:latest
    networks:
      - alchemyex_network
    container_name: 'alchemyex_redis'
    command: redis-server --appendonly yes --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 2s
      retries: 30
    volumes:
      - redis_data:/data
  alchemyex_pgadmin:
    image: dpage/pgadmin4:6.15
    container_name: alchemyex_pgadmin
    ports:
      - '${PGADMIN_PORT}:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: alchemyex@admin.com
      PGADMIN_DEFAULT_PASSWORD: alchemyexadmin
    volumes:
        - pgadmin:/var/lib/pgadmin
    depends_on:
      - alchemyex_db
    networks:
      - alchemyex_network

networks:
  alchemyex_network:
    driver: bridge

volumes:
  pg:
  redis_data:
  pgadmin:
    driver: local